name: Labeler
on: [pull_request, push]

jobs:
    label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Label Syncer
      uses: micnncim/action-label-syncer@v1.3.0
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
